### ISSUE TITLE
Actividad 3, cuadro comparativo 

### ISSUE THREAD

**Issue by Abisaylopez** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Abisaylopez#2]
[Cuadro comparativo METODO CIENTIFICO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Abisaylopez/files/9526250/Cuadro.comparativo.METODO.CIENTIFICO.pdf)

Abisay López Mendoza 1bs

**Comment by josealfredo79** [comment]
Este trabajo esta incompleto debe hacerse con minimo 5 columnas...

**Comment by PedroGarcia11439** [comment]
15% Seria la calificación basado en la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
